kind: Pod
apiVersion: v1
metadata: 
  name: nginx1
  labels:
   name: multi-container 
spec:
  containers:
   - name: nginx 
     image: nginx
   - name: almalinux
     image: almalinux:9
     command: [ "sleep" , "2000"]