kind: Pod
apiVersion: v1
metadata: 
  name: resources
  labels:
   name: expense-project
spec:
  containers:
    - name : nginx
      image: nginx
      resources:
       request:
        cpu: "100m"
        memory: "128Mi"
       limit:
        cpu: "100m"
        memory: "128Mi"